
    - name: install package for ha 
      yum: 
        name: "{{item}}"
      loop: "{{hapkage}}"
      when: inventory_hostname in groups['masters']
    - name: config the keepalive service 
      copy: 
        remote_src: no 
        src: keepalived.conf
        dest: /etc/keepalived/keepalived.conf
      when: inventory_hostname in groups ['k8smaster1']
    - name: config the keepalive1 service 
      copy: 
        remote_src: no 
        src: keepalived1.conf
        dest: /etc/keepalived/keepalived.conf 
      when: inventory_hostname in groups ['k8smaster2']
    - name: copy the script for keepalive 
      copy: 
        remote_src: no 
        src: check_apiserver.sh
        dest: /etc/keepalived/check_apiserver.sh
      when: inventory_hostname in groups['masters']
    - name: change file permissions 
      file: 
        path: /etc/keepalived/check_apiserver.sh
        mode: +x 
      when: inventory_hostname in groups['masters']
    - name: config the haproxy service 
      copy: 
        remote_src: no 
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      when: inventory_hostname in groups['masters']
    - name: start and enable service
      systemd: 
        name: "{{item}}" 
        state: started
        enabled: yes 
      loop: "{{hapkage}}"
      when: inventory_hostname in groups['masters']
        
